name:                node-editor
version:             0.1.0.0
synopsis:            Luna node editor
homepage:            www.luna-lang.org
license:             AllRightsReserved
author:              New Byte Order <contact@luna-lang.org>
maintainer:          New Byte Order <contact@luna-lang.org>

default-extensions:
  - AllowAmbiguousTypes
  - ApplicativeDo
  - Arrows
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - DuplicateRecordFields
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - LiberalTypeSynonyms
  - MonadComprehensions
  - MultiWayIf
  - NamedWildCards
  - NegativeLiterals
  - NoImplicitPrelude
  - NumDecimals
  - OverloadedLabels
  - OverloadedStrings
  - PackageImports
  - QuasiQuotes
  - RankNTypes
  - RecursiveDo
  - RelaxedPolyRec
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators
  - ViewPatterns

ghc-options:
  - -Wall
  - -O2
  - -fsimpl-tick-factor=1000
  # - -DDEBUG_PERF

dependencies:
  - "base >= 4.9 && < 4.10"
  - aeson
  - binary
  - bytestring
  - common
  - containers
  - convert
  - datetime
  - deepseq
  - extra
  - filepath
  - fuzzy-text
  - ghcjs-base
  - ghcjs-prim
  - hashable
  - lens
  - luna-studio-common
  - luna-lexer
  - luna-node-editor-view
  - matrix
  - mtl
  - random
  - react-flux
  - scientific
  - split
  - text
  - time
  - transformers
  - unordered-containers
  - uuid
  - uuid-types
  - vector
  - vector-text

executables:
  node-editor:
    main:             Main.hs
    source-dirs:      src
