_config/lib: !include "../config/hpack-common.yaml"

name        : luna-core
version     : 0.0.6
synopsis    : Luna Core
category    : Data
license     : Apache-2.0
stability   : experimental
homepage    : https://github.com/luna/luna
bug-reports : https://github.com/luna/luna/issues
author      : Luna Team
copyright   : Copyright (C) 2018 Luna Team
maintainer:
    - Wojciech Danilo  <wojciech.danilo@luna-lang.org>
    - Marcin Kostrzewa <marcin.kostrzewa@luna-lang.org>
    - Piotr Moczurad   <piotr.moczurad@luna-lang.org>

ghc-options:
    - -Wall
    - -O2

library:
    source-dirs:
        - src
    dependencies:
        - async
        - base
        - bytestring
        - container
        - containers
        - convert
        - data-default
        - deepseq
        - functor-utils
        - ghc
        - layered-state
        - lens
        - lens-utils
        - luna-autovector
        - luna-cpp-containers
        - luna-data-construction
        - luna-data-property
        - luna-data-storable
        - luna-data-tag
        - luna-data-typemap
        - luna-exception
        - luna-foreign-utils
        - luna-generic-traversable
        - luna-memory-manager
        - luna-memory-pool
        - luna-nested-containers
        - luna-syntax-definition
        - luna-th-builder
        - luna-tuple-utils
        - luna-type-cache
        - luna-typelevel
        - monad-branch
        - monoid
        - mtl
        - primitive
        - prologue >= 3.0.0
        - random
        - split
        - storable-tuple
        - template-haskell
        - transformers
        - vector

benchmarks:
    array-benchmark:
        main: Main.hs
        source-dirs:
            - test/bench
        c-sources:
            - test/bench/cbits/*.cpp
        include-dirs:
            - test/bench/cbits
        extra-libraries: stdc++
        cc-options: -std=c++14 -O3
        ghc-options:
            - -rtsopts
            - -threaded
            - -with-rtsopts=-N
            - -with-rtsopts=-T
        dependencies:
            - ansi-terminal
            - base
            - convert
            - criterion >= 1.3.0.0
            - deepseq
            - ghc
            - layered-state
            - luna-autovector
            - luna-core
            - luna-cpp-containers
            - luna-data-storable
            - luna-data-typemap
            - luna-exception
            - luna-foreign-utils
            - luna-generic-traversable
            - luna-generic-traversable2
            - luna-memory-manager
            - luna-memory-pool
            - luna-tuple-utils
            - mtl
            - prologue
            - unboxed-ref >= 0.4.0.0
            - vector
            - containers
            - structs
            - primitive

tests:
    spec:
        main: Main.hs
        source-dirs:
            - test/spec
        ghc-options:
            - -rtsopts
            - -threaded
            - -with-rtsopts=-N
            - -with-rtsopts=-T
        dependencies:
            - base
            - container
            - containers
            - hspec
            - hspec-expectations-lifted
            - luna-core
            - luna-cpp-containers
            - luna-data-storable
            - luna-exception
            - luna-foreign-utils
            - luna-generic-traversable
            - luna-typelevel
            - prologue
            - random

default-extensions: *luna-extensions

