name: typelevel
version: 1.2.3
synopsis: Useful type level operations (type families and related operators).
category: Data
license: Apache-2.0
stability: experimental
homepage: https://github.com/luna/typelevel
bug-reports: https://github.com/luna/typelevel/issues
author: Luna Team
copyright: Copyright (C) 2018 Luna Team
maintainer: Wojciech Danilo <wojciech.danilo@luna-lang.org>

ghc-options:
- -Wall
- -O2

library:
  source-dirs:
  - src
  dependencies:
  - base >= 4.9 && < 4.13
  - exceptions
  - lens
  - mtl
  - pretty
  - pretty-show
  - primitive
  - transformers
  - constraints
  - convert

default-extensions:
- AllowAmbiguousTypes
- ApplicativeDo
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DoAndIfThenElse
- DuplicateRecordFields
- EmptyDataDecls
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- LambdaCase
- MonadComprehensions
- MultiWayIf
- NamedWildCards
- NegativeLiterals
- NumDecimals
- OverloadedLabels
- PackageImports
- QuasiQuotes
- PatternSynonyms
- RankNTypes
- RecursiveDo
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators
- UnicodeSyntax
- ViewPatterns
- LiberalTypeSynonyms
- RelaxedPolyRec
