_config/lib: !include "../../../config/hpack-common.yaml"

name       : luna-syntax-text-model
version    : "0.1"
author     : Luna Team <contact@luna-lang.org>
maintainer : Luna Team <contact@luna-lang.org>

library:
    source-dirs:
        - src

dependencies:
    - base
    - containers
    - layered-state
    - lens-utils
    - luna-core
    - luna-nested-containers
    - luna-syntax-definition
    - luna-text-processing
    - prologue
    - vector-text

default-extensions: *luna-extensions

