#!/usr/bin/env python3

import scripts_build.atom_prepare
import scripts_build.atom_apm
import scripts_build.copy_configs
import scripts_build.stack_build
import os
import subprocess

app_dir      = scripts_build.atom_prepare.prep_path('..')
backend_dir  = scripts_build.atom_prepare.prep_path('../build/backend')
frontend_dir = scripts_build.atom_prepare.prep_path('../luna-studio')

def main ():
    try:
        scripts_build.stack_build.run()
        scripts_build.atom_prepare.run()
        scripts_build.atom_apm.run() # RENAME: LunaStudioInstallInAtom ?
        scripts_build.copy_configs.run()

    except subprocess.CalledProcessError:
        print("Status : FAIL")


main()
