author: Wojciech Danilo
bug-reports: https://github.com/wdanilo/data-construction/issues
category: Text
copyright: Copyright (C) 2015 Wojciech Danilo
default-extensions: [ConstraintKinds, DataKinds, DefaultSignatures, DeriveDataTypeable,
  DeriveFoldable, DeriveFunctor, DeriveGeneric, DeriveTraversable, DoAndIfThenElse,
  EmptyDataDecls, FlexibleContexts, FlexibleInstances, GeneralizedNewtypeDeriving,
  InstanceSigs, LambdaCase, MultiParamTypeClasses, OverloadedStrings, StandaloneDeriving,
  TemplateHaskell, TupleSections, TypeOperators, ViewPatterns, TypeFamilies]
dependencies: [base >=4.6 && <4.10, lens, data-rtuple, typelevel, text]
ghc-options: [-Wall, -O2]
homepage: https://github.com/wdanilo/data-construction
library:
  exposed-modules: [Data.Construction, Data.Phantom]
  source-dirs: src
license: Apache-2.0
maintainer: Wojciech Danilo <wojciech.danilo@gmail.com>
name: data-construction
stability: stable
synopsis: Data construction abstractions including Constructor, Destructor, Maker,
  Destroyer, Producer and Consumer.
version: 1.1.8
