resolver: lts-12.6

ghc-options:
  $locals:
    -O2
    -Wall
    -Wno-name-shadowing
    -fmax-worker-args=1000
    -fsimpl-tick-factor=400
    -fspec-constr-keen
    -fspecialise-aggressively
    -fstatic-argument-transformation
    -funbox-strict-fields
    -threaded
  $everything:
    -fconstraint-solver-iterations=100

extra-deps:
    - cond-0.4.1.1
    - container-1.1.5
    - convert-1.5
    - functor-utils-1.17.1
    - impossible-1.1.3
    - lens-utils-1.4.5
    - monad-branch-1.0.3
    - monoid-0.1.8
    - prologue-3.2.4
    - typelevel-1.2.2
    - layered-state-1.1.4
    - git: 'git@github.com:luna/nested-containers.git'
      commit: 8b37f1fbcb7e4cada7b8e28e0778f73c7b69f0a8
    - git: 'git@github.com:luna/luna.git'
      commit: 1f5f7194f371ea17df3c2f56f1c85a8eb6f3a320
      subdirs:
          - lib/data-typemap
          - lib/th-builder
          - lib/tuple-utils
          - lib/typelevel

