name:               luna-manager
version:            "1.1.5"
author:             New Byte Order <contact@newbyteorder.com>
maintainer:         New Byte Order <contact@newbyteorder.com>

dependencies:
  - aeson
  - aeson-pretty
  - ansi-terminal
  - ascii-progress
  - base
  - base64-bytestring
  - bytestring
  - conduit
  - conduit-extra
  - constraints
  - containers
  - cryptonite
  - cryptonite-conduit
  - dependent-state
  - directory
  - errors
  - exceptions
  - file-embed
  - filepath
  - http-conduit
  - http-types
  - io-streams
  - lens
  - lens-utils
  - monad-control
  - mtl
  - network
  - network-uri
  - optparse-applicative
  - path
  - prologue
  - process
  - resourcet
  - safe
  - safe-exceptions
  - shelly
  - signal
  - split
  - system-filepath
  - template-haskell
  - temporary
  - text
  - time
  - transformers
  - typed-process
  - typelevel
  - unordered-containers
  - uuid
  - yaml

default-extensions:
    - AllowAmbiguousTypes
    - ConstraintKinds
    - DataKinds
    - DefaultSignatures
    - DeriveGeneric
    - DuplicateRecordFields
    - FlexibleContexts
    - FlexibleInstances
    - FunctionalDependencies
    - GeneralizedNewtypeDeriving
    - LambdaCase
    - NoImplicitPrelude
    - OverloadedStrings
    - RankNTypes
    - ScopedTypeVariables
    - StandaloneDeriving
    - TemplateHaskell
    - TupleSections
    - TypeApplications
    - TypeFamilies
    - TypeOperators


executables:
  luna-manager:
    main:          Main.hs
    source-dirs:   src
    ghc-options: -threaded -Wunused-imports
