#!/bin/sh
set -e
set -x

if [ "$#" -ne 1 ]
then
  echo "Promote drone build to alpha users"
  echo "Usage: promote-build (build-number)"
  exit 1
fi

BUILD_NUMBER=$1

echo "Promoting build #$BUILD_NUMBER..."

SRC=lunalang/luna-testing:staging-b$1
DST1=lunalang/luna:latest
DST2=lunalang/luna:b$1

docker pull $SRC
docker tag -f $SRC $DST1
docker tag $SRC $DST2
docker push $DST1
docker push $DST2

echo "Finished, successfully!"
