#!/bin/bash

[ -f "luna-shell.sh" ] && source "luna-shell.sh"

# ensure that all the requirements are satisfied:
pip3 install --user -r requirements.txt > /dev/null 2>&1
python3 scripts_build/build.py "$@"
