FROM alpine
MAINTAINER kamil.figiela@luna-lang.org

RUN    apk update \
    && apk add s6 nginx mercurial g++ \
    && adduser -u 82 -D -S -G www-data www-data

COPY docker/s6/frontend /etc/s6/frontend
COPY docker/s6/common /etc/s6/common
CMD /bin/s6-svscan /etc/s6/frontend

COPY docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY docker/nginx/frontend/nginx-default /etc/nginx/sites-enabled/default
EXPOSE 80

COPY nodelab/www /usr/share/nodelab/gui

