name:                node-editor
version:             0.1.0.0
synopsis:            Luna node editor
homepage:            www.luna-lang.org
license:             AllRightsReserved
author:              New Byte Order <contact@newbyteorder.com>
maintainer:          New Byte Order <contact@newbyteorder.com>

default-extensions:
  - BangPatterns
  - ConstraintKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - ViewPatterns

ghc-options:
  -Wall -O2 -fsimpl-tick-factor=1000

dependencies:
  - "base >= 4.9 && < 4.10"
  - aeson
  - binary
  - bytestring
  - common
  - containers
  - convert
  - datetime
  - deepseq
  - extra
  - ghcjs-base
  - ghcjs-prim
  - hashable
  - lens
  - luna-studio-common
  - luna-syntax-text-lexer
  - matrix
  - mtl
  - random
  - react-flux
  - scope-searcher
  - split
  - text
  - time
  - transformers
  - unordered-containers
  - uuid-types
  - vector
  - vector-text

executables:
  node-editor:
    main:             Main.hs
    source-dirs:      src
