author: Wojciech Danilo
category: Data
default-extensions: [ConstraintKinds, DataKinds, DefaultSignatures, DeriveDataTypeable,
  DeriveFoldable, DeriveFunctor, DeriveGeneric, DeriveTraversable, DoAndIfThenElse,
  EmptyDataDecls, FlexibleContexts, FlexibleInstances, GeneralizedNewtypeDeriving,
  InstanceSigs, LambdaCase, MultiParamTypeClasses, OverloadedStrings, StandaloneDeriving,
  TemplateHaskell, TupleSections, TypeOperators, ViewPatterns, TypeFamilies]
dependencies: [base, convert, data-construction, deepseq, lens, lens-utils, impossible,
  ghc-prim]
github: https://github.com/wdanilo/layer
library: {ghc-options: -Wall -O2, source-dirs: src}
license: Apache-2.0
maintainer: Wojciech Danilo <wojciech.danilo@gmail.com>
name: data-layer
stability: experimental
synopsis: Data layering utilities. Layer is a data-type which wrapps other one, but
  keeping additional information. If you want to access content of simple newtype
  object, use Lens.Wrapper instead.
version: 1.0.13
