_config/lib: !include "../../../config/hpack-common.yaml"

name       : luna-syntax-text-prettyprint
version    : "0.1"
author     : Luna Team <contact@luna-lang.org>
maintainer : Luna Team <contact@luna-lang.org>

library:
    source-dirs:
        - src

dependencies:
    - base
    - layered-state
    - layouting
    - luna-core
    - luna-cpp-containers
    - luna-data-storable
    - luna-syntax-definition
    - luna-syntax-text-lexer
    - luna-syntax-text-parser
    - luna-syntax-text-model
    - prologue
    - text

default-extensions: *luna-extensions

