resolver: lts-12.16
name: luna

packages:
    - githash-0.1.3.0
    - hspec-expectations-lifted-0.10.0
    - hspec-megaparsec-1.1.0
    - megaparsec-6.5.0
    - neat-interpolation-0.3.2.2
    - perf-0.4.1.0
    - placeholders-0.1
    - rdtsc-1.3.0.1

    - container-1.1.6
    - convert-1.5.1
    - functor-utils-1.17.2
    - impossible-1.1.4
    - layered-state-1.1.5
    - layouting-1.1.4
    - lens-utils-1.4.6
    - monad-branch-1.0.4
    - monoid-0.1.9
    - prologue-3.2.6
    - terminal-text-1.1.2
    - typelevel-1.2.3
    - vector-text-1.1.6

    - git: "git@github.com:fpco/weigh.git"
      commit: aabc37b4a4d9cc2fed236714e345394a60a18310

