name:                text-editor
version:             0.1.0.0
synopsis:            Luna code editor backend
homepage:            www.luna-lang.org
license:             AllRightsReserved
author:              New Byte Order <contact@luna-lang.org>
maintainer:          New Byte Order <contact@luna-lang.org>

default-extensions:
  - BangPatterns
  - ConstraintKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - ScopedTypeVariables
  - TemplateHaskell
  - TypeApplications

ghc-options:
  - -O2
  - -Wall
  # - -DDEBUG_PERF

dependencies:
  - "base >= 4.9 && < 4.10"
  - aeson
  - binary
  - bytestring
  - common
  - containers
  - datetime
  - ghcjs-base
  - ghcjs-prim
  - lens
  - luna-studio-common
  - luna-lexer
  - mtl
  - prologue
  - random
  - text
  - text-processing
  - time
  - transformers
  - uuid
  - uuid-types
  - vector-text



executables:
  text-editor:
    main:             Main.hs
    source-dirs:      src
