_config/lib: !include "../config/hpack-common.yaml"

name:       luna-runtime
version:    "0.1"
author:     Luna Team <contact@luna-lang.org>
maintainer: Luna Team <contact@luna-lang.org>


library:
    source-dirs:
        - src

dependencies:
    - async
    - base
    - containers
    - luna-core
    - luna-future
    - mtl
    - prologue

default-extensions: *luna-extensions

