name: layouting
version: 1.1.4
synopsis: General layouting library. Currently supports layouting 2D areas and can
  be used as a backend for text pretty printing or automatic windows layouting managers.
category: Data
license: Apache-2.0
stability: experimental
homepage: https://github.com/luna/layouting
bug-reports: https://github.com/luna/layouting/issues
author: Luna Team
copyright: Copyright (C) 2018 Luna Team
maintainer: Wojciech Danilo <wojciech.danilo@luna-lang.org>

ghc-options:
- -Wall
- -O2

library:
  source-dirs:
  - src
  dependencies:
  - base >= 4.9 && < 4.13
  - prologue
  - text
  - terminal-text
  - layered-state
  - container

default-extensions:
- AllowAmbiguousTypes
- ApplicativeDo
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DoAndIfThenElse
- DuplicateRecordFields
- EmptyDataDecls
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- InstanceSigs
- LambdaCase
- MonadComprehensions
- MultiWayIf
- NamedWildCards
- NegativeLiterals
- NoImplicitPrelude
- NumDecimals
- OverloadedLabels
- PackageImports
- QuasiQuotes
- PatternSynonyms
- RankNTypes
- RecursiveDo
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators
- UnicodeSyntax
- ViewPatterns
- LiberalTypeSynonyms
- RelaxedPolyRec
