resolver: lts-8.11
compiler: ghcjs-0.2.1.9008011_ghc-8.0.2
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9008011_ghc-8.0.2:
        url: https://github.com/matchwood/ghcjs-stack-dist/raw/master/ghcjs-0.2.1.9008011.tar.gz
        sha1: a72a5181124baf64bcd0e68a8726e65914473b3b

ghc-options:
  node-editor: -DGHCJS_BROWSER
  text-editor: -DGHCJS_BROWSER
extra-deps:
  - cond-0.4.1.1
  - datetime-0.3.1
  - ghcjs-dom-0.7.0.4
  - ghcjs-dom-jsffi-0.7.0.4
  - foundation-0.0.7

packages:
- {location: ./node-editor}
- {location: ./text-editor}
- {extra-dep: true, location: ./lib}
- {extra-dep: true, location: ./node-editor-view}
- {extra-dep: true, location: ../libs/luna-studio-common}
- extra-dep: true
  location: {commit: 61ff909efd466735cd4820f9ab2c564e324b5546, git: 'git@github.com:luna/container.git'}
- extra-dep: true
  location: {commit: b84f6fcc7b466760327b1d0f2e7150d9f78dfdc6, git: 'git@github.com:luna/convert.git'}
- extra-dep: true
  location: {commit: a6afda3b96efe00938aba61ac12a2f5f2134ff3d, git: 'git@github.com:luna/data-construction.git'}
- extra-dep: true
  location: {commit: 8a5773adba33d71a311ba0b4123b744213b0be91, git: 'git@github.com:luna/data-layer.git'}
- extra-dep: true
  location: {commit: b5f02ced2912501d923c07950789fbcf44a6a9ce, git: 'git@github.com:luna/data-prop.git'}
- extra-dep: true
  location: {commit: 9da4c9b2534693cfe82adeb37f12eaadacb41e62, git: 'git@github.com:luna/data-repr.git'}
- extra-dep: true
  location: {commit: 4f5153aed4944317942ff9025c79f7fc3be85181, git: 'git@github.com:luna/data-rtuple.git'}
- extra-dep: true
  location: {commit: 8c3d63bb78c24fcfadd22efe1a0b8071c4240ff6, git: 'git@github.com:luna/dependent-state.git'}
- extra-dep: true
  location: {commit: 1c6a4fd165e4b15cad114b0a554e0974fd119223, git: 'git@github.com:luna/functor-utils.git'}
- extra-dep: true
  location: {commit: a846dd3481b24ff1933db1e121db9c511f4c6edf, git: 'git@github.com:luna/fuzzy-text.git'}
- extra-dep: true
  location: {commit: a1606cccc12cb521acbc598e52c481b9054b42a7, git: 'git@github.com:luna/impossible.git'}
- extra-dep: true
  location: {commit: 3ba7d5da78aab023fc74c44fc7445ffab0bc18e0, git: 'git@github.com:luna/lens-utils.git'}
- extra-dep: true
  location: {commit: bfd3f25a617308fe7eabd012019413e7eb8cdcb6, git: 'git@github.com:luna/luna.git'}
  subdirs: [syntax/text/lexer]
- extra-dep: true
  location: {commit: e63e373d67cd8dd7c179a618f5d32f6ffb3abdd3, git: 'git@github.com:luna/monoid'}
- extra-dep: true
  location: {commit: 7c7a6d657e7db8c3dcd80fbed0a7e02e02f43ae3, git: 'git@github.com:luna/monad-branch'}
- extra-dep: true
  location: {commit: cbcd88c87e8888ebfeacd258cca96b3d6d489d35, git: 'git@github.com:luna/parsert'}
- extra-dep: true
  location: {commit: c1c525d71b5e749f24e26f71d2d1a68019cae850, git: 'git@github.com:luna/prologue.git'}
- extra-dep: true
  location: {commit: ad94b1f2e4bc87b81853ff746b64c59b3eae7f09, git: 'git@github.com:luna/react-flux'}
- extra-dep: true
  location: {commit: fe9834f3f5583086d76b12779a1c2a5290c72b0d, git: 'git@github.com:luna/text-processing.git'}
- extra-dep: true
  location: {commit: 107db9368e95e192d70c0dec274ecfe3592101d2, git: 'git@github.com:luna/typelevel.git'}
- extra-dep: true
  location: {commit: ed546316cdd896467276913a45073a0cb9e447b2, git: 'git@github.com:luna/vector-text.git'}
- extra-dep: true
  location: {commit: ddfcd1e0372b93e947b380b911c123fe67227b21, git: 'git@github.com:luna/visualization-api.git'}
